name: Generate Weekly Report

on:
  schedule:
    - cron: '0 12 * * 1'  # Executa toda segunda-feira às 12:00 UTC
  push:
    branches:
      - dev
      - main

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install @octokit/rest axios

      - name: Generate daily commits report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          REPO_OWNER: "fabsoftwareitp" 
          REPO_NAME: "fabsoftware.itp.ifsp.edu.br"
          DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1293896643980300342/SOcnqX8neZRZcA1dyF2YvWlwrPPWPH8CRPH60Mg_KVLCurAk0a7AbFDp4fnNb4pul24d 
        run: node generate_daily_commits_report.js

      - name: Generate issues by assignee report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          REPO_OWNER: "fabsoftwareitp" 
          REPO_NAME: "fabsoftware.itp.ifsp.edu.br"
          ORG_NAME: "fabsoftwareitp"
          DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1293896643980300342/SOcnqX8neZRZcA1dyF2YvWlwrPPWPH8CRPH60Mg_KVLCurAk0a7AbFDp4fnNb4pul24d
        run: node generate_issues_by_assignee_report.js