name: Deploy GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - name: Install Dependencies
      run: |
        npm ci # or yarn install if using Yarn

    - name: Build
      run: |
        npm run build

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "./public/*"
        target: "/var/www/sitefabrica"
        strip_components: 1

    - name: Deploy GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }} 
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public